
name: 🔂 Teardown Mozaic-React PR Preview

on:
  pull_request:
    types: closed

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: storybook-static
          teardown: 'true'
